<?php 

    require __DIR__ . '/../config/connexion.php';
    
    if (isset($_GET['id'])) {
        $userId =  $_GET['id'];
    }
    
    $query = $db->prepare('SELECT * FROM users WHERE id = :id');
    $parameters = [':id' => $userId];
    $query->execute($parameters);

    $user = $query->fetch(PDO::FETCH_ASSOC);


?>


<main class="container py-5">
    <h1>
        Modifier un utilisateur
    </h1>
    <form class="mt-5" action="logic/edit-user.php" method="POST">
        <input type="hidden" id="userId" name="id" value="<?= $userId ?>" />
        <fieldset>
            <label for="email" class="form-label">Email</label>
            <input type="email" id="email" name="email" class="form-control" value="<?= $user['email'] ?>" />
        </fieldset>
        <fieldset>
            <label for="password" class="form-label">Mot de passe</label>
            <input type="password" id="password" name="password" class="form-control" value="<?= $user['password'] ?>" />
        </fieldset>
        <fieldset>
            <label for="first_name" class="form-label">Prénom</label>
            <input type="text" id="first_name" name="first_name" class="form-control" value="<?= $user['first_name'] ?>" />
        </fieldset>
        <fieldset>
            <label for="last_name" class="form-label">Nom</label>
            <input type="text" id="last_name" name="last_name" class="form-control" value="<?= $user['last_name'] ?>" />
        </fieldset>
        <button type="submit" class="mt-3 btn btn-primary">Sauvegarder</button>
    </form>
</main>